framework:
    secret: '%env(APP_SECRET)%'
    session: true

    asset_mapper:
        paths:
            - assets/styles
            - assets/js
            - assets/webfonts

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
