parameters:
    app_url: '%env(APP_URL)%'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

framework:
    mailer:
        envelope:
            sender: 'tom.ochietti@gmail.com'
