parameters:
    app_url: '%env(APP_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

# === CONFIG MAILER POUR UTILISER GMAIL COMME EXPEDITEUR ===
framework:
    mailer:
        envelope:
            sender: 'tom.ochietti@gmail.com'
